### ISSUE TITLE
Add Zeroize

### ISSUE THREAD

**Issue by burdges** [w3f/ring-vrf#14]
Ideally via either https://github.com/zkcrypto/ff/pull/22 or https://github.com/scipr-lab/zexe/issues/111 although using Secret type seems like overkill.

**Comment by swasilyev** [comment]
What should be zeroized?

**Comment by burdges** [comment]
All secret key types really.  I partially did this already: https://github.com/w3f/ring-vrf/blob/master/src/keys.rs#L78
