### ISSUE TITLE
Proposal to separate code from papers

### ISSUE THREAD

**Issue by davxy** [w3f/ring-vrf#69]
I propose to move the folders containing research related papers and material to a separate repo (or vice versa).

The main motivation is to better follow the changes which are affecting the code.

The folders I'm talking about are `papers` and `talks`.

**Comment by burdges** [comment]
Yeah, this was an experiment.  It didn't work as well as I'd have liked.  I'll split the repos.

**Comment by burdges** [comment]
I've not actually openned the other repo it seems but this will definitely happen.
